### ISSUE TITLE
Version 5.0.0 has 4.0.0 in drivermetadata.xml

### ISSUE THREAD

**Issue by arueth** [QualiSystems/Cisco-IOS-Shell#19]
The version 5.0.0 release has 4.0.0 in the drivermetadata.xml:

<Driver Name="Generic Cisco IOS Driver Version3" Version="4.0.0" MainClass="cisco_ios_resource_driver.CiscoIOSResourceDriver" Description="Generic driver for all IOS devices">

**Comment by GalcQuali** [comment]
Thanks - we will fix it for the next release.

**Comment by Costya-Y** [comment]
Fixed
