### ISSUE TITLE
Issue when using router as switch

### ISSUE THREAD

**Issue by graboskyc** [QualiSystems/Cisco-IOS-Shell#20]
When using a 7604, for example, each interface must have "switchport" on the interface before our system can provision the VLAN and access mode. Can this be added to the shell so that less provisioning must be done prior to using CloudShell?

**Comment by graboskyc** [comment]
Tested on 7604 runing version: 

Cisco IOS Software, c7600rsp72043_rp Software (c7600rsp72043_rp-ADVIPSERVICESK9-                                                                                       M), Version 15.4(3)S4, RELEASE SOFTWARE (fc1)

ROM: System Bootstrap, Version 12.2(33r)SRE, RELEASE SOFTWARE (fc1)
BOOTLDR: Cisco IOS Software, c7600rsp72043_rp Software (c7600rsp72043_rp-ADVIPSE                                                                                        RVICESK9-M), Version 15.4(3)S4, RELEASE SOFTWARE (fc1)

**Comment by GalcQuali** [comment]
Thanks - issue will be fixed in the next release and also for 2 gen IOS router shell.

**Comment by GalcQuali** [comment]
Issue is fixed and released for 1st and 2nd gen shells.
